development:
  host: 'pub-redis-14201.us-east-1-3.6.ec2.redislabs.com'
  port: 14201
  password: 'conekta'

production:
  host: 'pub-redis-14201.us-east-1-3.6.ec2.redislabs.com'
  port: 14201
  password: 'conekta'

test:
  host: 'pub-redis-14201.us-east-1-3.6.ec2.redislabs.com'
  port: 14201
  password: 'conekta'